app:
  mode: "local"

logger:
  log_level: "info"
  log_output: ""

db: # host=localhost user=postgres password=rootroot dbname=Aviasales port=5433 sslmode=disable
  host: "localhost"
  user: "postgres"
  password: "rootroot"
  port: 5433
  database: "Aviasales"
  migration: true

http_server:
  address: "localhost"
  port: "9999"
